# Generated by Django 5.0.4 on 2026-04-07 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex color code (e.g., #FFFFFF).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, default="", max_length=50000),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
    ]
